default_language_version:
    python: python3.8

repos:
    - repo: https://github.com/psf/black
      rev: 21.10b0
      hooks:
        - id: black
          args:
            - --line-length=160

    - repo: https://github.com/pycqa/pylint
      rev: pylint-2.6.0
      hooks:
        - id: pylint
          args:
            - app/
            - --max-line-length=120
            - --rcfile=.pylintrc
          verbose: true
