default_language_version:
    python: python3.8

repos:
    - repo: https://github.com/psf/black
      rev: 21.10b0
      hooks:
        - id: black
          args:
            - --line-length=160
    - repo: local
      hooks:
        - id: pylint
          name: pylint
          entry: bash -c 'pylint app --rcfile=.pylintrc; exit 0'
          language: python
          verbose: true
          pass_filenames: false
