name: Create Release Branch
on:
  workflow_dispatch:
    inputs:
      branch:
        description: Target Branch
        type: choice
        required: true
        default: 'release'
        options:
          - release
          - hotfix
      version:
        description: Target Version (ex. 220101)
        type: string
        required: true

jobs:
  create-release-branch:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        ref: develop
        token: ${{ secrets.ACTION_TOKEN }}

    - name: Initialize git config
      run: |
        git config --global url.https://${{ secrets.REPO_TOKEN }}@github.com/.insteadOf https://github.com/
        git config user.name "GitHub Actions"
        git config user.email noreply@github.com

    - name: Create release or hotfix branch
      run: git checkout -b ${{ github.event.inputs.branch }}/v${{ github.event.inputs.version }}

    - name: Update Target Branch
      uses: fjogeleit/yaml-update-action@main
      with:
        valueFile: '.github/workflows/deploy_ci.yml'
        propertyPath: 'on.push.branches'
        value: release/v${{ github.event.inputs.version }}
        updateFile: true
        createPR: false
        commitChange: false

    - name: Update Image Version
      uses: fjogeleit/yaml-update-action@main
      with:
        valueFile: '.github/workflows/deploy_ci.yml'
        propertyPath: 'env.VERSION'
        value: v${{ github.event.inputs.version }}_${{ github.sha }}
        updateFile: true
        createPR: false
        commitChange: false

    - name: Push new branch
      run: |
        git add .github/workflows/deploy_ci.yml
        git commit -m "v${{ github.event.inputs.version }} QA 배포"
        git push origin ${{ github.event.inputs.branch }}/v${{ github.event.inputs.version }}

    - name: Create pull request into main
      uses: thomaseizinger/create-pull-request@1.0.0
      with:
       github_token: ${{ secrets.GITHUB_TOKEN }}
       head: release/v${{ github.event.inputs.version }}
       base: master
       title: v${{ github.event.inputs.version }} into master
       body: |
           This PR was created in response workflow running.
           I've updated the version name and code commit: ${{ steps.make-commit.outputs.commit }}.

    - name: Create pull request to develop
      uses: thomaseizinger/create-pull-request@1.0.0
      with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          head: release/v${{ github.event.inputs.version }}
          base: develop
          title: v${{ github.event.inputs.version }} into develop
          body: |
              This PR was created in response workflow running.
              I've updated the version name and code commit: ${{ steps.make-commit.outputs.commit }}.

    - name: Send success message to Slack
      uses: archive/github-actions-slack@v2.0.0
      with:
        slack-bot-user-oauth-access-token: ${{ secrets.SLACK_MESSAGE_TOKEN }}
        slack-channel: C02CEFHFL82
        slack-text: ✅ ${{ github.event.inputs.branch }}/v${{ github.event.inputs.version }} 브랜치가 생성되었습니다.
      if: ${{ job.status }} == "success"

    - name: Send failed message to Slack
      uses: archive/github-actions-slack@v2.0.0
      with:
        slack-bot-user-oauth-access-token: ${{ secrets.SLACK_MESSAGE_TOKEN }}
        slack-channel: C02CEFHFL82
        slack-text: ⚠️ ${{ github.event.inputs.branch }}/v${{ github.event.inputs.version }} 브랜치 생성에 실패했습니다.
      if: ${{ job.status }} != "success"
