name: Create Release Branch
on:
  workflow_dispatch:
    inputs:
      branch:
        description: Target Branch
        type: choice
        required: true
        default: 'release'
        options:
          - release
          - hotfix
      version:
        description: Target Version (ex. 220101)
        type: string
        required: true

jobs:
  create-release-branch:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        ref: develop

    - name: Create release or hotfix branch
      run: git checkout -b ${{ github.event.inputs.branch }}/v${{ github.event.inputs.version }}

    - name: Initialize git config
      run: |
       git config user.name "GitHub Actions"
       git config user.email noreply@github.com

    - name: Update Target Branch
      uses: fjogeleit/yaml-update-action@main
      with:
        valueFile: '.github/workflows/deploy_ci.yaml'
        propertyPath: 'on.push.branches'
        value: release/v${{ github.event.inputs.version }}
        updateFile: true
        branch: release/v${{ github.event.inputs.version }}
        createPR: false
        commitChange: false
        message: '${{ github.event.inputs.versionName }} QA 배포'

    - name: Update Image Version
      uses: fjogeleit/yaml-update-action@main
      with:
        valueFile: '.github/workflows/deploy_ci.yaml'
        propertyPath: 'env.VERSION'
        value: v${{ github.event.inputs.version }}_${{ github.sha }}
        updateFile: true
        branch: release/v${{ github.event.inputs.version }}
        createPR: false
        commitChange: true
        message: '${{ github.event.inputs.versionName }} QA 배포'

    - name: Push new branch
      run: git push origin release/v${{ github.event.inputs.versionName }}

    - name: Create pull request into main
      uses: thomaseizinger/create-pull-request@1.0.0
      with:
       GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
       head: release/v${{ github.event.inputs.versionName }}
       base: master
       title: v${{ github.event.inputs.versionName }} into master
       body: |
           This PR was created in response workflow running.
           I've updated the version name and code commit: ${{ steps.make-commit.outputs.commit }}.

    - name: Create pull request to develop
      uses: thomaseizinger/create-pull-request@1.0.0
      with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          head: release/v${{ github.event.inputs.versionName }}
          base: develop
          title: v${{ github.event.inputs.versionName }} into develop
          reviewers: ${{ github.event.issue.user.login }}
          body: |
              This PR was created in response workflow running.
              I've updated the version name and code commit: ${{ steps.make-commit.outputs.commit }}.
