name: QA(INHOUSE) CI pipeline
'on':
  push:
    branches: release/v220801
env:
  VERSION: v220801_641eae0f4140db14e07c7fc281269cbf535f5bee
  IMAGE_NAME: test
  env: test
jobs:
  build:
    name: Test, Build, Push, Commit
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
