name: QA(INHOUSE) CI pipeline
'on':
  push:
    branches: release/v220919
env:
  VERSION: v220919_ef9db776b59a29f1ebf8d8eb9b2aed10b29dc4a0
  IMAGE_NAME: test
  env: test
jobs:
  build:
    name: Test, Build, Push, Commit
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
