name: QA(INHOUSE) CI pipeline
'on':
  push:
    branches: release/v220909
env:
  VERSION: v220909_993964015d19cfbe9a053ede080a72f1b32bf83f
  IMAGE_NAME: test
  env: test
jobs:
  build:
    name: Test, Build, Push, Commit
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
