name: Pytest

on:
  pull_request:
    branches: [ develop ]

jobs:
  linting:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: reviewdog/action-black@v2
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        reporter: github-pr-review
        level: warning

  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install Poetry
      run: |
        pip install -U pip
        pip install pytest-cov
        pip install wheel
        pip install poetry
      env:
        POETRY_VIRTUALENVS_CREATE: false

    - name: Cache dependencies
      id: cache
      uses: actions/cache@v2
      with:
        path: ~/.cache/pypoetry/virtualenvs
        key: ubuntu-poetry-poetry.lock

    - name: Install dependencies
      if: steps.cache.outputs.cache-hit != 'true'
      run: |
        python -m pip install --upgrade poetry
        poetry config virtualenvs.create false
        poetry install --no-root

    - name: Run pytest
      run: |
        pytest --junitxml=pytest.xml --cov-report=term-missing:skip-covered --cov=app tests/ | tee pytest-coverage.txt

    - name: Pytest coverage comment
      id: run-test
      uses: MishaKav/pytest-coverage-comment@main
      with:
        pytest-coverage-path: ./pytest-coverage.txt
        junitxml-path: ./pytest.xml
        create-new-comment: true

    - name: Get Error
      if: steps.run-test.outputs.errors > 0 || steps.run-test.oupts.failures > 0
      run: exit 1
