name: Pytest

on:
  pull_request:
    branches: [ develop ]

jobs:
  formatting:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: reviewdog/action-black@v2
      with:
        reporter: github-pr-review
        level: warning

  pylint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: dciborow/action-pylint@0.0.3
        with:
          reporter: github-pr-review
          level: warning

  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install pip
      run: |
        pip install pytest-cov
        pip install wheel
        pip install poetry
        poetry install --no-root
      env:
        POETRY_VIRTUALENVS_CREATE: false

    - name: Run pytest
      run: |
        PHASE=test pytest --junitxml=pytest.xml --cov-report=term-missing:skip-covered --cov=app tests/ | tee pytest-coverage.txt

    - name: Pytest coverage comment
      id: run-test
      uses: MishaKav/pytest-coverage-comment@main
      with:
        pytest-coverage-path: ./pytest-coverage.txt
        junitxml-path: ./pytest.xml
        create-new-comment: true

    - name: Get Error
      if: steps.run-test.outputs.errors > 0 || steps.run-test.oupts.failures > 0
      run: exit 1
