name: Test
on:
  pull_request:
    branches: [ develop ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install Poetry
      run: |
        pip install -U pip
        pip install pytest-cov
        pip install wheel
        pip install poetry
        poetry install
      env:
        POETRY_VIRTUALENVS_CREATE: false

    - name: Build coverage file
      run: |
        pytest --cache-clear --cov=app tests/ > pytest-coverage.txt
    - name: Comment coverage
      uses: coroo/pytest-coverage-commentator@v1.0.2
