name: Pytest

on:
  pull_request:
    branches: [ develop ]

jobs:
  test:
    name: Test
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Poetry Install
        run: |
          pip install wheel
          pip install poetry
          poetry install --no-root
        env:
          POETRY_VIRTUALENVS_CREATE: false
      - name: Run Pytest
        run: |
          PHASE=test pytest tests

  build:
    name: Test, Build, Push, Commit
    runs-on: ubuntu-18.04
    needs: [ test ]
    steps:
      - name: Checkout Infra Repository
        uses: actions/checkout@v2
        with:
          repository: jisoo1170/k8s-study
          token: ${{ secrets.REPO_TOKEN }}
          path: infra-repo
      - name: Update Infra Repository
        run: |
          cd infra-repo
          git config user.name github-actions
          git config user.email github-actions@github.com
          date > generated2.txt
          git add .
          git commit -m "Add > generated"
          git push
