name: Pytest

on:
  pull_request:
    branches: [ develop ]

jobs:
  build:
    name: Test, Build, Push, Commit
    runs-on: ubuntu-18.04
    steps:
    - name: update infra repo
    - uses: actions/checkout@v2
      with:
        repository: jisoo1170/k8s-study
        token: ${{ secrets.REPO_TOKEN }}
        path: infra-repo
    - run: |
        git config user.name github-actions
        git config user.email github-actions@github.com
        date > generated.txt
        git add .
        git commit -m "Add > generated"
        git push origin master
