name: Pytest

on:
  pull_request:
    branches: [ develop ]

jobs:
  formatting:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: reviewdog/action-black@v2
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        reporter: github-pr-review
        level: warning

  pylint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: reviewdog/action-setup@v1
        with:
          reviewdog_version: latest

      - name: Set up Python 3.8
        uses: actions/setup-python@v1
        with:
          python-version: 3.8

      - name: Setup pylint
        run: |
          python -m pip install --upgrade pip
          pip install pylint
          pylint --generate-rcfile > ~/.pylintrc

      - name: Run reviewdog
        env:
          REVIEWDOG_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          pylint --rcfile=~/.pylintrc app/*.py | reviewdog -efm="%f:%l:%c: %m" -reporter=github-pr-review -level=warning

  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install pip
      run: |
        pip install pytest-cov
        pip install wheel
        pip install poetry
        poetry install --no-root
      env:
        POETRY_VIRTUALENVS_CREATE: false

    - name: Run pytest
      run: |
        PHASE=test pytest --junitxml=pytest.xml --cov-report=term-missing:skip-covered --cov=app tests/ | tee pytest-coverage.txt

    - name: Pytest coverage comment
      id: run-test
      uses: MishaKav/pytest-coverage-comment@main
      with:
        pytest-coverage-path: ./pytest-coverage.txt
        junitxml-path: ./pytest.xml
        create-new-comment: true

    - name: Get Error
      if: steps.run-test.outputs.errors > 0 || steps.run-test.oupts.failures > 0
      run: exit 1
